<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class TaskController extends Controller
{
    //
    public function index(){
//        return view('viewTest',['id'=>123]);
        return Route::currentRouteAction();
    }

    public function getParam($param){
        return "this is param ".$param;
    }

    public function url(){
        $url = route('task.getParam',['id'=>"ss"],false); //返回路由地址
        return redirect($url);
    }

//    public function middleware($middleware, array $options = [])
//    {
//        return parent::middleware($middleware, $options); // TODO: Change the autogenerated stub
//    }


}
